### ISSUE TITLE
Impossible to create an array of arrays type

### ISSUE THREAD

**Issue by Mykybo** [colyseus/schema#10]
Imagine you have a board in game with x and y axis. You want a 2d array in your state.

Right now the only way to achieve this is this: 
```
class Row extends Schema {
  @type(['number'])
  items
}
class Board extends Schema {
  @type([ Row ])
}
```
Which means you would then have to access each cell like: `board[12].items[3]` instead of just `board[12][3]`.

Or am I missing something obvious?

**Comment by endel** [comment]
That's currently not supported https://github.com/colyseus/schema#limitations-and-best-practices

**Comment by Mykybo** [comment]
Do you plan on adding support for them? Otherwise I will stick with the fossil schema.

**Comment by endel** [comment]
@Mykybo eventually, yes! First the new schema serializer needs to be stable across all platforms, I'm having a bad time porting the [decoder to C++](https://github.com/colyseus/schema/blob/5f7561a7d8dd3aeab0d98f56f817120abc3aede9/decoders/cpp/schema.h) 😭

**Comment by endel** [comment]
For now, you can have a flattened array instead of being multi-dimensional, for example, which is a pretty common solution people use. Based on the `width` of the map, you can access the x/y based on an iteration value.

**Comment by endel** [comment]
So far there are no plans on supporting this, if you need a 2D/3D array, please check this reference on how to compact them into a 1D array https://softwareengineering.stackexchange.com/questions/212808/treating-a-1d-data-structure-as-2d-grid
