### ISSUE TITLE
ArraySchema.splice() items to insert are ignored

### ISSUE THREAD

**Issue by larsschwegmann** [colyseus/schema#101]
I'm trying to replace a value in an ArraySchema at a certain position. The obvious choice was the `splice()`method.

After looking at the [code](https://github.com/colyseus/schema/blob/6213126d4e3cc88469bbb457f5ab078978931b0f/src/types/ArraySchema.ts#L289), it seems that the third argument is completely ignored by the splice implementation. Is this intended? The documentation clearly states "Changes the contents of an array by removing or **replacing existing elements** and/or adding new elements in place.".

Also, the [JS Array splice method](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/splice) allows for replacing elements. I would suggest adding support for replacing items or changing the method signature + documentation, because that behavior seems pretty confusing.

**Comment by endel** [comment]
Hi @larsschwegmann, this is still a missing feature on `ArraySchema#splice()`. Pull requests are welcome to include this feature on `@colyseus/schema`. Cheers!

**Comment by sylvainpolletvillard** [comment]
I think I fixed it with https://github.com/colyseus/schema/pull/159

**Comment by endel** [comment]
Oh right! Thank you @sylvainpolletvillard, let's close this :D Happy new year! ✨
