### ISSUE TITLE
The @type({array: PrimitiveType}) syntax is accepted in TS for ArraySchema fields, but does not actually work

### ISSUE THREAD

**Issue by jldinh** [colyseus/schema#110]
According to the following snippet, the `@type({array: PrimitiveType})` syntax is accepted for ArraySchema fields.
https://github.com/colyseus/schema/blob/d3ce63db3ca6a8e1c3f5dbdd60bd7d71c416d8c8/src/annotations.ts#L26-L31

However, using it does not work properly, as mutations of the ArraySchema are not handled, and do not trigger updates to the client.
From what I could see, doing something like `arraySchema[i] = "bar"` creates a `i` property on the Proxy object instead of the underlying data.

Using the `@type([PrimitiveType])` syntax works fine.

**Comment by endel** [comment]
Hi @jldinh! Thanks for reporting, just released version `@colyseus/schema@1.0.25`, can you please check if that works for you now? Cheers!

**Comment by jldinh** [comment]
Sorry, it's taken a while for me to respond, but I can confirm it now works for me! Thanks!
