### ISSUE TITLE
Map of arrays Schema

### ISSUE THREAD

**Issue by dondragon2** [colyseus/schema#111]
is there a way to define a map of array values in the schema?

`{ key: [...values] }`

**Comment by endel** [comment]
Hi @dondragon2,

`MapSchema` only supports having primitive types or schema references as values. 

One "workaround" for that could be using a `Schema` as the value type, and define your `ArraySchema` inside that reference:

```typescript
class ArrayHolder extends Schema {
  @type(["string"]) myArray = new ArraySchema<string>();
}

class State extends Schema {
  @type({ map: ArrayHolder }) holders = new MapSchema<ArrayHolder>();
}
```
