### ISSUE TITLE
game room disposed but game state class still running

### ISSUE THREAD

**Issue by hdev72** [colyseus/schema#117]
hello every body

after my game room called ondispose and no body in the room game state class still running...

how can i destroy the game state class?
i just set the new GameState class in onCreate of room
is it destroy automaticly? or gamestate classes will stack 

my loop with setTimeOut in game state doesnt stops and still running
i stoped the loop with change a boolean (disposed true) in game state class  from onDispose room

thanks for your helps

**Comment by hdev72** [comment]
up

**Comment by endel** [comment]
Hi @hdev72,

> my loop with setTimeOut in game state doesnt stops and still running

If you use `this.clock.setTimeout()` or `this.clock.setInterval()` the interval is cleared automatically when the room is disposed. You probably have a memory leak by a native interval not being cleared when the room is disposed. Make sure to not have any active reference to the room and/or to the state in memory so they are removed from memory.

See https://www.toptal.com/nodejs/debugging-memory-leaks-node-js-applications
