### ISSUE TITLE
ArraySchema reduce with no initial parameter uses undefined as first element

### ISSUE THREAD

**Issue by lfsmoura** [colyseus/schema#118]
ArraySchema `reduce` behaves differently than Javascript's Array reduce. When no `initialValue` is provided, the first call to callback function get's `undefined` as accumulator instead of the first element.

To fix that on https://github.com/colyseus/schema/blob/master/src/types/ArraySchema.ts instead of passing ahead the value of initial parameter, you can do something like `Array.from(this.$items.values()).apply(this, arguments);`

**Comment by endel** [comment]
Thank you for the suggestion @lfsmoura ❤️
