### ISSUE TITLE
FIFO Array Schema Extension

### ISSUE THREAD

**Issue by keldaan-ag** [colyseus/schema#123]
Colyseus is amazing. Thanks @endel for your work and your community support.

# Summary

This is a request for a First In First Out Array Schema extension

## Motivation

Lets say we have a game with a main lobby, a place where players chat with each others.

First solution: we can use a simple `broadcast` when a player send a message in the chat

```js
this.broadcast("message", incomingMessage);
```

But we also want the messages to be persistant. This way the players that were in a game room (and therefore not in the lobby room)  can see messages posted in the lobby afterwards.

Second solution: we can use an `arraySchema` to store the messages. Every time a message is sent by a player, we add a message in the arraySchema

```js
this.state.messages.push(new Message(incomingMessage);
```

Problems comes with a big spike of users, resulting in a big amount of messages sent in the lobby, slowing down the loading of lobby interface for every player entering the lobby (due to a big number of elements in the arraySchema).

We can consider that old messages are useless, and only, lets say, the last 50 or 100 messages are interesting for the players.

With a FIFO schema, this case would be fully resolved and would look like this:

```js
this.messages = new schema.FifoSchema(50); // defining the size of the FIFO
```

The FIFO mechanism will auto delete the old messages and prevent any overgrowth in the messages schema.

**Comment by hunkydoryrepair** [comment]
did you try using `ArraySchema.shift`. That is intended to remove the first element, presumably without needing to send the full array down the pipe.
