### ISSUE TITLE
Concat in ArraySchema

### ISSUE THREAD

**Issue by CocosGames** [colyseus/schema#134]
Trying to connect one ArraySchema with another one, got the error:
Error: a 'number' was expected, but '[2,4,2,2,3,4,1,4,5,5,4,1]' (ArraySchema) was provided in ArraySchema#6

**Comment by CocosGames** [comment]
I got a workaround and got to know what's happening:
when 2 array are joining into one ArraySchema, there would be chances to insert NaNs into.
so the workaround would be simple: push, unshift, do not use concat.

**Comment by endel** [comment]
Hi @CocosGames, would you mind adding a failing test case to reproduce this? SImilar to this one: https://github.com/colyseus/schema/blob/master/test/ArraySchemaTest.ts#L1348-L1352

**Comment by CocosGames** [comment]
Hi @endel , sorry I thought an ArraySchema can concat another ArraySchema.
arr.concat([4, 5, 6]);  √
arr.concat(arr); ×
arr.concat(arr.toJSON()); √
I think it's better to introduce more details in documents.
