### ISSUE TITLE
Breaking change to MapSchema type in 1.0.36

### ISSUE THREAD

**Issue by foolmoron** [colyseus/schema#140]
Hey there, our dependency automatically updated to 1.0.36 and caused these breaking changes. The change itself seems fine but I couldn't find any docs on this, so it seems accidental. I had to check the source code here to figure out what happened.
```
src/requests/state.ts:115:9 - error TS2322: Type 'MapSchema<string>' is not assignable to type 'MapSchema<string, string>'.
  Property '$changes' is protected but type 'MapSchema<V>' is not a class derived from 'MapSchema<V, K>'.
115         data: new MapSchema<string>(),
```

**Comment by endel** [comment]
Hey @foolmoron, can you share more of your source code? I'm not sure if this is a general breaking change or if specific to your case

**Comment by foolmoron** [comment]
Hmm I'm not sure what happened actually. I deleted my node_modules and rebuilt and it's fine now. Nevermind!
