### ISSUE TITLE
`schema-codegen`  input fileName with wildcard 

### ISSUE THREAD

**Issue by yiming0** [colyseus/schema#148]
follow the docs: 

https://github.com/colyseus/docs/blob/aefbf8f162b01eb1c5d93fabff21daec26246fbb/docs/state/schema-callbacks.md#L326-L334

the `codegen/parser`  dose not support wildcard yet: 

https://github.com/colyseus/schema/blob/4b7410dd8f700ffc671af91802cac346de77bdf4/src/codegen/parser.ts#L228-L272

*PS: is that windows shell probrem? 🤔*

**Comment by endel** [comment]
Thanks for the PR, this is out on [2.0.8](https://www.npmjs.com/package/@colyseus/schema/v/2.0.8)
