### ISSUE TITLE
Getting an Uncaught TypeError in the colyseus.js

### ISSUE THREAD

**Issue by DownyDude** [colyseus/schema#16]
I am getting this errors in the colyseus.js file
```
Uncaught TypeError: h is not a constructor
    at Function.t.decode (colyseus.js:formatted:3325)
    at e.handshake (colyseus.js:formatted:2906)
    at e.onMessageCallback (colyseus.js:formatted:1156)
    at t.value (colyseus.js:formatted:2267)
Uncaught TypeError: Cannot read property 'decode' of undefined
    at e.setState (colyseus.js:formatted:2892)
    at e.setState (colyseus.js:formatted:1165)
    at e.onMessageCallback (colyseus.js:formatted:1139)
    at t.value (colyseus.js:formatted:2267)
```

I tried to debug a little bit and found that the error is caused by an undefined "rootType" in this section `var h = u[i.rootType], f = new h;`

To reproduce the error just use the example as in the doc:

const schema = require('@colyseus/schema');
const Schema = schema.Schema;
const MapSchema = schema.MapSchema;
const type = schema.type;

class Player extends Schema {
}
type("number")(Map.prototype, "x");
type("number")(Map.prototype, "y");

class PlayersState extends Schema {
    constructor () {
        super();
        this.players = new MapSchema();
    }
}
type({ map: Player })(PlayersState.prototype, "players");

class PlayersRoom extends Room {
  onInit (options) {
    this.setState(new PlayersState());
  }
  /* 
  ...
  */
}

In the client side, connect to the room and listen to the room.sate.players.

P.S: I am not using Typescript, only javascript.

**Comment by endel** [comment]
hey @DownyDude, the `@colyseus/schema` package has been updated recently. if you're using the dist `colyseus.js` file, please download it again. Make sure you have the latest version in the server, too!

**Comment by endel** [comment]
Also, maybe this is not correct:

```javascript
class Player extends Schema {
}
type("number")(Map.prototype, "x");
type("number")(Map.prototype, "y");
```

You may have meant `Player.prototype` here. Cheers

**Comment by DownyDude** [comment]
Yes, I am using the last dist.
When I switch back to the previous version, it works just fine but with that other error for strings longer than 31.

**Comment by endel** [comment]
@DownyDude please remove your `node_modules` and `package-lock.json` and install them again. Then using the latest dist file you should be fine!

Sorry about this, I didn't wanted to bump a version of all clients because of this change.

**Comment by DownyDude** [comment]
Thank you for your support but I am still getting the error.
I am deploying to heroku, so I did a `heroku repo:reset` and downloaded the last colyseus.js one more time again  and changed `Map.prototype` to `Player.prototype` but the problem still the same.

**Comment by endel** [comment]
@DownyDude have you removed `node_modules`, `package-lock.json` and re-installed the modules? Heroku will get exactly the package versions described in `package-lock.json`, it should say in there that it's using `@colyseus/schema@0.4.29`

**Comment by DownyDude** [comment]
Yes, I did that twice now.
And checked for @colyseus/schema@0.4.29

**Comment by DownyDude** [comment]
My bad... I was doing that on another dyno, apologize.
So, you were right, now that's all updated to the latest versions (colyseus 0.10.7, @colyseus/schema 0.4.29, colyseus.js 0.10.5) it's working without the error.
Thank you and please close this issue.
