### ISSUE TITLE
[Feature]: Add return type to ArraySchema.filter

### ISSUE THREAD

**Issue by DinoCloudlet** [colyseus/schema#172]
### Description & Use case

Is there a reason why the filter Method of ArraySchema has no return Value defined in the first case of the overloads?

Could there be V[] be defined like in the first case:

```typescript 
    filter(callbackfn: (value: V, index: number, array: V[]) => unknown, thisArg?: any): V[]
    filter<S extends V>(callbackfn: (value: V, index: number, array: V[]) => value is S, thisArg?: any): V[] {
        return Array.from(this.$items.values()).filter(callbackfn, thisArg);
    }
```

**Comment by endel** [comment]
Thank you for the feedback @DinoCloudlet - I've just applied your suggestion and released a new version 🙌
