### ISSUE TITLE
share state with worker thread

### ISSUE THREAD

**Issue by amir-arad** [colyseus/schema#20]
Hi
I'm experiencing some high CPU usage in the game loop, running physics and collision detection. I thought I'd separate that engine to a node wiorker, seeing as it's designed to take advantage of js buffers (shares the same memory instead of serializing it).

would love to hear your opinion on the most performant way to approach that.

**Comment by endel** [comment]
hey @amir-arad, what do you see in the profiler, what're the highest time-consuming function calls?

I don't have experience with the new `worker_threads` module on Node.js, I'm afraid it's not that simple to move the schema states into the worker threads and sync them back to the main thread. I'm up to suggestions though!

**Comment by amir-arad** [comment]
no need to profile, my simulation is to blame :)
I'm testing a room with 1K entities, and my loop calculates their position according to velocity vectors, and then detects collisions (using `detect-collisions` npm module). 

I'm still not comfortable with this project's code to make intelligent constructive suggestions ;(
