### ISSUE TITLE
ArraySchema<number>: Not initializing properly with one index

### ISSUE THREAD

**Issue by vacarsu** [colyseus/schema#28]
when initializing an ```ArraySchema<number>``` with 1 value in the array, it initializes empty. This only appears to be an issue with ```Array<number>```, I do not see this issue with ```Array<string>```.
```javascript
class State extends Schema {
  @type(['number']) numbers: ArraySchema<number>;
  constructor(numbers = [1]) {
    super();
    this.numbers = new ArraySchema(...numbers);
    console.log(this.numbers); // output: ArraySchema [ <1 empty item> ]
  }
}
```

**Comment by endel** [comment]
Hi @vacarsu,

The `ArraySchema` extends from `Array`, so you get the same behaviour as a regular `Array` in JavaScript: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#Syntax

```javascript
var arrayOfNumbers = new Array(1);
// => [empty]

var arrayOfNumbers = new Array(1, 2, 3);
// => (3) [1, 2, 3]
```
