### ISSUE TITLE
Add codegen for Java

### ISSUE THREAD

**Issue by endel** [colyseus/schema#30]
@doorbash has done an amazing job to port the schema de-serializer to Java (https://github.com/doorbash/colyseus-java/releases/tag/2.0.0), now it would be great that the `schema-codegen` tool could convert TypeScript schema files into Java.

- https://gist.github.com/doorbash/445310840227fd51d75f2da4f4e4b8a6
- https://gist.github.com/doorbash/8621303acf9375f7e295e88196a86061

**Comment by endel** [comment]
hey @doorbash, I've added a `--java` option now, I haven't tested all options, maybe arrays and maps of primitive types will need to be fixed. Cheers! 🤗 

![Screenshot 2019-07-17 at 10 57 15](https://user-images.githubusercontent.com/130494/61381591-a7255500-a881-11e9-85df-578cf032ec3b.png)

**Comment by doorbash** [comment]
That's great @endel Thank you!

There is some issue with it though I list them here :
![image](https://user-images.githubusercontent.com/5982526/61385803-571db100-a8c8-11e9-8e9f-0b964f385d53.png)

1. 
`public ArraySchema<> players = new ArraySchema<>(Player.class);`

needs to be changed to 

`public ArraySchema<Player> players = new ArraySchema<>(Player.class);`

2. 
`public MapSchema<> cells = new MapSchema<>(Cell.class);`

to 

`public MapSchema<Cell> cells = new MapSchema<>(Cell.class);`

3.
```
@SchemaField("3/map")	
public MapSchema<int> map_1 = new MapSchema<int>();
```

to 

```
@SchemaField("3/map/int32")	
public MapSchema map_1 = new MapSchema();
```

4.
```
@SchemaField("4/array/int32")	
public ArraySchema<int> array_1 = new ArraySchema<int>();
```

to 

```
@SchemaField("4/array/int32")	
public ArraySchema array_1 = new ArraySchema();
```


Here is `state.ts` file I used to test codegen:
https://gist.github.com/doorbash/c07960944e3628a130375604dff132f4

**Comment by endel** [comment]
Thanks @doorbash, I've made some changes and it should be exactly as you described now! Let me know if anything still needs to change. Cheers!

**Comment by doorbash** [comment]
Fixed now. Thank you @endel You're awesome 🤗
