### ISSUE TITLE
toJSON() should be rescursive for nested Schema properties.

### ISSUE THREAD

**Issue by ishnu47** [colyseus/schema#34]
Could you please implement the toJSON() method to have recursion call for other nested Schema properties inside a Schema?

**Comment by ishnu47** [comment]
Thank you for your update @endel 
Btw, does this fix take care of ArraySchema and MapSchema?

Great thanks!

**Comment by endel** [comment]
Hi @ishnu47, yes, you can see in the test case that I'm checking for `ArraySchema` and `MapSchema` output as well: https://github.com/colyseus/schema/commit/65eb8513e1c293b9f3f049b9212640f16e2648e7#diff-214fc4f0b1289e310eff363a501563c5R1117-R1139
