### ISSUE TITLE
Add codegen for Typescript

### ISSUE THREAD

**Issue by marcoklein** [colyseus/schema#38]
Hi,

Is the codegen for Typescript already final? I run `schema-codegen ./src/server/schema/GameState.ts --output ./src/client/schema/ --ts` to generate the client schema. It seems to work properly, but won't generate anything if the class is empty.

In my last project I simply included the server side defined GameState.ts. However, this gives various unnecessary functions within my client (both TS based). 
As I had to look through the source code to find this feature, I would open a Pull Request if appropriate to update the documentation:

```
# C#/Unity
schema-codegen ./schemas/State.ts --output ./unity-project/ --cs

# C/C++
schema-codegen ./schemas/State.ts --output ./cpp-project/ --cpp

# Haxe
schema-codegen ./schemas/State.ts --output ./haxe-project/ --hx

# Typescript
schema-codegen ./schemas/State.ts --output ./typescript-project/ --ts
```

Cheers

**Comment by endel** [comment]
Hi @marcoklein, thanks for reporting, version `@colyseus/schema@0.4.55` has been published fixing this. Now you can have a class that extends `Schema` without any properties, and the codegen should generate it successfully. Cheers!

**Comment by endel** [comment]
I've added the updated options in the docs, if you'd like to contribute to it, there's a button to edit any page here 
 
![Screenshot 2019-09-03 at 10 56 46](https://user-images.githubusercontent.com/130494/64179480-a0569f80-ce39-11e9-8234-cfa1f0c24c6e.png)

**Comment by marcoklein** [comment]
Thank you @endel - haven't had a look inside the Colyseus docs.
