### ISSUE TITLE
Schema deep cloning

### ISSUE THREAD

**Issue by ishnu47** [colyseus/schema#39]
Hello, I think we need this update:
Schema cloning should support deep cloning: property is a Schema object or collection objects (ArraySchema, MapSchema) should also be deeply cloned. This will make sure the changed states of the Schema is reseted and fully de-coupled from the original Schema object.

Thank you.

**Comment by endel** [comment]
Thanks for reporting @ishnu47, this has been fixed now on `@colyseus/schema@0.4.56`.

Test-case for this can be found here: https://github.com/colyseus/schema/blob/e7eb93de42a7362bccd8cc8c65878baebd20a9f5/test/SchemaTest.ts#L1117-L1146

**Comment by ishnu47** [comment]
Thank you very much!
