### ISSUE TITLE
"type" field in JSON as protected keyword

### ISSUE THREAD

**Issue by etherny** [colyseus/schema#4]
Type field name look protected keyword but rise an unexpected error : 

https://github.com/colyseus/schema/blob/master/src/codegen/parser.ts#L18

Reproduce : 
Add any json anywhere in code extending Schema, exemple : 
 this.state.broadCastMessage({
            type: "ACTION",
            from: player.hero.properties.id
        });

Code generation via NPX rise this error : 

```Cannot read property 'find' of undefined```

**Comment by endel** [comment]
@etherny thanks for reporting, I'm going to check this soon.
