### ISSUE TITLE
Error ocured when in Schemas use word "type" for var names

### ISSUE THREAD

**Issue by kimonniez** [colyseus/schema#49]
Error ocured when in Schemas use word "type" for var names

**Comment by kimonniez** [comment]
I tried to fix this issue but can't push my branch for create pull request.
Solution for this bug is add restrictions in `node.getText() === "defineTypes"` condition 
`
} else if (
                node.getText() === "defineTypes" &&
                node.parent.kind !== ts.SyntaxKind.ImportSpecifier &&
                node.parent.kind !== ts.SyntaxKind.BindingElement &&
                node.parent.kind !== ts.SyntaxKind.Parameter &&
                node.parent.kind !== ts.SyntaxKind.CallExpression &&
                node.parent.kind !== ts.SyntaxKind.TemplateSpan &&
                node.parent.kind !== ts.SyntaxKind.SwitchStatement
            ) {
`

**Comment by endel** [comment]
Hi @kimonniez, thanks for reporting, can you provide how your Schema file looked like so I can reproduce this issue you had?

Thanks!

**Comment by kimonniez** [comment]
Actually I changed my code for now, but you can reproduce bug by this pseudoclass of Scema:
```
class Test extends Schema {
    constructor() {
        super()
    }

    someProblemMethod(type) {
        switch (type) {
            case 1:
                //logic
                break;
            case 2:
                //logic
                break;
            default:
                throw new Error('Dummy error');
        }
    }
}
```

Problem is in using word `type` as method argument.

**Comment by endel** [comment]
Hi @kimonniez, can you try the latest version to check if it works now? `@colyseus/schema@0.5.7`
