### ISSUE TITLE
Language agnostic schema definition

### ISSUE THREAD

**Issue by serjek** [colyseus/schema#55]
Would be great to have language agnostic schema definition (in yaml may be?) This would allow developers to create their own schema builders for their own client and server extern implementations.

Motivation: as I maintain haxe server externs I find it difficult to keep schemas on server and client side in sync. Having them defined in single source of truth would be a huge improvement. I would happily create schema-codegen for haxe server externs if there is a schema definition out there.

**Comment by endel** [comment]
Hi @serjek, are you using Haxe for both client-side, and server-side? I think it should be possible to re-use the same definitions on both sides. If that's not currently possible, I believe it would be better to fix just that. Adding a new layer would increase the overall complexity :(
