### ISSUE TITLE
Error on ArraySchema splicing

### ISSUE THREAD

**Issue by ftruzzi** [colyseus/schema#60]
Hi, and thank you for your work!

I'm having issues with splicing an ArraySchema of a custom data type that extends Schema.

```
TypeError: Cannot read property 'deleteIndex' of undefined
    at /home/ftruzzi/projects/.../server/node_modules/@colyseus/schema/lib/types/ArraySchema.js:125:33
    at Array.map (<anonymous>)
    at ArraySchema.splice (/home/ftruzzi/projects/.../server/node_modules/@colyseus/schema/lib/types/ArraySchema.js:121:22)

```

Looking at `ArraySchema.js:125`, it looks like `$changes` has no `parent` property in my case. Adding a check and skipping the line makes the splicing work, but I have no idea of the consequences.

Thank you!

**Comment by endel** [comment]
Hi @ftruzzi, can you post the full code where this issue is happening? There are a few tests for [`ArraySchema#splice` here](https://github.com/colyseus/schema/blob/master/test/ArraySchemaTest.ts), which are working fine. Maybe there is some additional operation that's causing the issue. Thanks!

**Comment by ftruzzi** [comment]
The code itself is almost only a splice call, but I'm very new to both the framework and TypeScript so I might be missing something else.

This is the function where the error originates:

```typescript
export function drawCards(cards: ArraySchema<Card>, n: number = 1) {
    if (cards.length < n) {
        console.error(`Could not draw ${n} cards from array of length ${cards.length}`);
        return undefined;
    }

    let drawn = cards.splice(0, n);

    return drawn;
}
```

and this is my `Card` class:

```typescript
export class Card extends Schema {
    @type("number")
    a: number;

    @type("string")
    b: string;

    @type("string")
    c: string;

    @type("boolean")
    d: boolean;

    constructor(props: any) {
        super();

        this.a = props["a"];
        this.b = props["b"];
        this.c = props["c"];
        this.d = false;
    }
}
```

Thanks!

**Comment by ftruzzi** [comment]
Sorry, this turned out to be an error on my side. I had the ArraySchema in a separate object (not the state), but that was a simple object that did not extend Schema.

Maybe it would be nice to add to the docs saying that you can't add ArraySchema and MapSchema properties to a regular object but only to subclasses of Schema.

I might have found an actual bug in .splice but I'll open a new issue.

Thank you!
