### ISSUE TITLE
1.0.0: Use Map internally for MapSchema

### ISSUE THREAD

**Issue by endel** [colyseus/schema#62]
The `MapSchema` currently acts like a plain object in JavaScript, which lacks lots of useful methods that a `Map` would provide.

For version `1.0.0`, the `MapSchema` should be re-structured to use a `Map`, and implement all methods of the `Map` structure: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

**Comment by endel** [comment]
It would be a big plus to use `tslint` custom transform to automatically "upgrade" existing projects, to convert old `MapSchema` calls to newer ones, such as:

```typescript
// old
const player = players["one"];
// new
const player = players.get("one");

// old
players["one"] = player;
// new
players.set("one", player);
```

**Comment by damian-pastorini** [comment]
Out of curiosity, use Map (or Set, also saw the other issue to include it), wouldn't affect performance over use Array?
And if that's the case, would this change be mandatory or could it be optional? Maybe you could keep all the different classes available for users choose which one suites us better?

**Comment by endel** [comment]
Hi @damian-pastorini, regarding performance only benchmarks can tell, but it should be very little difference by using one or another (Map, Set, or Array).

I'll try to keep both syntaxes for maps so people upgrading won't feel much difference. When https://github.com/colyseus/schema/issues/75 lands, it should be possible to use either `map.get("key")` or `map["key"]`. But only `map.get("key")` will return the right type in TypeScript (https://github.com/colyseus/schema/issues/3)
