### ISSUE TITLE
1.0.0 Proposal: Support for JSON objects or out out the box deserialization of certain data types 

### ISSUE THREAD

**Issue by virtumonde** [colyseus/schema#67]
One idea for a new feature would be out the box deserialization of certain data types, for example, serializing and deserializing JSON objects into strings or even better – supporting them by default via string conversion or a different method. (I am not sure which method because I don't know why it is not possible to support object in the schema by default in the first place).

**Comment by virtumonde** [comment]
I just realized that it's easy to do this via JSON.stringify() and JSON.parse() but it would be nice to have this serialization and deserialization done under the hood or support it by default.

**Comment by endel** [comment]
This is going to be hard to implement on C#
