### ISSUE TITLE
Deep fields are blank when using MapSchema

### ISSUE THREAD

**Issue by SuperLanceur** [colyseus/schema#73]
Hello ! I tried to find a solution to this for a few hours but I had no luck. I think it may be an issue with this, let me explain. I am using this with Colyseus 0.13
When I join a room I listen for every callback 
```javascript
function join(){
    client.joinOrCreate("test", {token: getCookie("token")}).then(room => {
        room.state.onChange = function(changes){
            changes.forEach(change => {
                console.log(change.field, change.value, change.previousValue);
            })
        }
        console.log("Connected")
    }).catch(e => {
        console.error(e)
    })
}
```
The server directly edits the state when a player joins
```typescript
onJoin (client: Client, options: any) {
        this.state.test()
}
```
```typescript
test() {
        let testStateSub: TestStateSub = new TestStateSub();
        testStateSub.test2 = "test1";
        let testState: TestState = new TestState();
        testState["test"] = testStateSub;
        this.testStateMap[1] = testState;
        testState.test3 = "4";
}
```
but when I listen for the changes, I have the following issues :

-  With the JavaScript client, `testStateSubMap` was empty, it had no child
- With the Unity client, `testStateSubMap` had a child, but the value was empty. Only the key was readable

In my state class I only have this
```typescript
@type({map: TestState})
testStateMap: MapSchema<TestState> = new MapSchema<TestState>();
```

and my `TestState` schema looks like this
```typescript
import { Schema, type, MapSchema } from "@colyseus/schema";
import { UserState } from "./UserState";

export class TestStateSub extends Schema{

    @type("string")
    test2:string = "waiting";

}
export class TestState extends Schema{

    @type("string")
    test3:string = "waiting";

    @type({map: TestStateSub})
    testStateSubMap = new MapSchema<TestStateSub>();
}
```

Sorry for the long issue. I tried to make it as complete as possible so it is easier to read.

**Comment by endel** [comment]
Hi @SuperLanceur 👋 

Can you check this you have the data available by listening for changes on the deep structure as well?

```typescript
room.state.testStateSubMap.onChange = function(instance, key) {
  console.log(instance, "available at", key);
}
```

I feel like the callbacks for getting changes in the client-side are a bit hard to understand at the moment, I really would like to change the approach for a new version, but still couldn't come up with something nice.

RXJS's [`BehaviourSubject`](https://www.learnrxjs.io/learn-rxjs/subjects/behaviorsubject) seems to be a good approach for listening for existing and new values changing over time, so I've been thinking to have something similar in the future.

**Comment by SuperLanceur** [comment]
Hello @endel ! Thanks for the fast reply 😄 
I can access `testStateSubMap` directly. I had to listen to `testStateMap` but even with that I can browse in the output using Firefox's tools and tell that testStateSubMap is empty. What makes me think that is this
```
_indexes: Map(0)
    size: 0
```
It wasn't empty using Schema with Unity though, even if the value was blank.
Am I missing something ?

**Comment by endel** [comment]
Version 0.14 has fixed similar issues to this one, I believe this also should've been fixed: https://github.com/colyseus/colyseus/releases/tag/0.14.0

Please feel free to reopen this issue if the problem persists!
