### ISSUE TITLE
v0.10 : value validation in schema 0.4.14

### ISSUE THREAD

**Issue by etherny** [colyseus/schema#8]
"5c9964165e8afb70f44bc762" look like string, isn't ?

```
        return _super !== null && _super.apply(this, arguments) || this;
                                         ^
Error: a 'string' was expected, but a '"5c9964165e8afb70f44bc762"' was provided.
```

**Comment by endel** [comment]
@etherny omg, do you have the full stack trace?

**Comment by etherny** [comment]
I found, just 5c9964165e8afb70f44bc762 is a mongodb ObjectId, but the log show the ToString value of the field value.

Proposal : add the field name. type and the current Schema name

**Comment by endel** [comment]
@etherny I've improved validation during encoding on `@colyseus/schema@0.4.15`

**Comment by etherny** [comment]
@endel the new version show this message : 

```
Error: a 'string' was expected, but '"5c9964165e8afb70f44bc762"' (ObjectID) was provided.
    at new EncodeSchemaError (D:\alteration - Copy\Server\node_modules\@colyseus\schema\lib\annotations.js:32:42)    at assertType (D:\alteration - Copy\Server\node_modules\@colyseus\schema\lib\annotations.js:40:15)
    at encodePrimitiveType (D:\alteration - Copy\Server\node_modules\@colyseus\schema\lib\annotations.js:66:17)
    at CreatureProperties.Schema.encode (D:\alteration - Copy\Server\node_modules\@colyseus\schema\lib\annotations.js:485:22)
```

Is it possible to show the Class name in message too, to avoid to search in the stack, In this exemple, `CreatureProperties`.

Proposal : 
`Error: a 'string' was expected, but '"5c9964165e8afb70f44bc762"' (ObjectID) was provided in CreatureProperties schema.`

**Comment by etherny** [comment]
New issue with type validation : 
If i use heritance for polymorphism in an ArraySchema or MapSchema i cannot add child class in this one.

```
class A extends Schema {}
class B extends A {}

class C extends Schema {
   @type(map: A) children = new MapSchema<A>();
}
```
I can add B in the map, but serializer rise an error.

`Error: a 'A' was expected, but 'B' was provided.`

**Comment by endel** [comment]
Hi @etherny! Unfortunately, this is not going to be supported for now, maybe in the future. So the error is correct. 

I could make B be serializable as A, without all B fields, but that doesn't help either. 

To make this happen, an additional byte would be needed during encoding to determine a different class usage, but that's not that simple with the current structure.

Cheers!

**Comment by etherny** [comment]
ok no problem, just to keep this in mind, i will find a work around for this.

**Comment by endel** [comment]
Thanks for the suggestion, now errors are reported as:

```
Error: a 'Player' was expected, but 'Object' was provided in MyState#arrayOfPlayers
```

**Comment by etherny** [comment]
Cool !
