### ISSUE TITLE
Error when using .map() instead of .forEach() on 0.14.0-alpha.2

### ISSUE THREAD

**Issue by virtumonde** [colyseus/schema#84]
Exactly the title. When I use `state.something.map()` I get this:
```
state.something.map is undefined
```
Everything works correctly when I use `.forEach()`

**Comment by endel** [comment]
Hi @virtumonde, which data type are you using there? 👀

**Comment by virtumonde** [comment]
I am using MapSchema:
```
class RoomState extends Schema {
  @type({ map : Player })
  players = new MapSchema<Player>();
}

```
export default class Player extends Schema {

    @type('string')
    sessionId: string;
    @type('number')
    lat: number;
    @type('number')
    lng: number;

    dLat: number;
    dLng: number;

    constructor(sessionId: string, lat: number, lng: number) {
        super()
        this.sessionId = sessionId;
        this.lat = lat;
        this.lng = lng;
        this.dLat = lat + 1;
        this.dLng = lng + 1;
    }

    setLngLat(lng: number, lat: number) {
        this.lng = lng;
        this.lat = lat;
    }

    update() {
        var line = lineString([[this.lng, this.lat], [this.dLng, this.dLat]]);        
        let updatedLngLatFeature = along(line, ONE_METER / PATCH_RATE, { units: 'degrees' });
        let updatedLngLat = updatedLngLatFeature.geometry.coordinates;
        this.setLngLat(updatedLngLat[0], updatedLngLat[1]);
        console.log(updatedLngLat);
    }
}
```

```

**Comment by virtumonde** [comment]
Can you check if you have the same error on your end? Also, I am using React Native.

**Comment by endel** [comment]
I see, the  [JavaScript Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) (and `MapSchema`) do not provide a `.map()` function. Only arrays have it afaik.

What you can do is use the `.values()`, `.keys()` or `.entries()` methods to turn your map into an array, and then perform the `.map()`:

```typescript
Array.from(yourMap.values()).map((value) => /* ... */)
```

**Comment by virtumonde** [comment]
@endel, thank you!
