### ISSUE TITLE
Empty schema causing errors because _schema is undefined

### ISSUE THREAD

**Issue by LelouBil** [colyseus/schema#85]
Hello, I was having a strange error while creating a room and I managed to narrow it down to having an empty schema class.

`TypeError: Invalid value used in weak set` in line 68 of SchemaSerializer.js, in the hasFilter function.

I'm not familiar enough with the code to submit a pr but I managed to found this while investigating the issue.

`knownSchemas.add(schema);` was giving the error because `schema` was `undefined`, because `_schema` of the class was undefined.

I tried adding a random property to my schema and `_schema` got defined. 

I think an empty schema should have `{}` instead of `undefined` for `_schema`. 

I don't actually know when or why it was `undefined` so I'm reporting the issue here.

**Comment by endel** [comment]
Hi @LelouBil, thanks for reporting. Version `0.14` of Colyseus is coming soon, along with an updated version of `@colyseus/schema` that should fix this, along with many other issues (#75, https://github.com/colyseus/schema/pull/82)
