### ISSUE TITLE
Typescript build fails with esnext/es2020 target in 1.0.0-alpha.24

### ISSUE THREAD

**Issue by will-hart** [colyseus/schema#86]
I'm just testing out colyseus 0.14 in a typescript project with target `esnest`. After upgrading to colyseus/colyseus-js `0.14-alpha`, and @colyseus/schema to `1.0.0-alpha.24` I receive the following eslint error when building:

```
ERROR  Failed to compile with 1 errors    

ERROR in .../node_modules/@colyseus/schema/lib/types/ArraySchema.d.ts(4,22):    
4:22 Class 'ArraySchema<V>' incorrectly implements interface 'V[]'.
  Type 'ArraySchema<V>' is missing the following properties from type 'V[]': flatMap, flat     
    2 | import { SchemaDecoderCallbacks } from "../Schema";
    3 | export declare function getArrayProxy(value: ArraySchema): ArraySchema<any>;
  > 4 | export declare class ArraySchema<V = any> implements Array<V>, SchemaDecoderCallbacks {
      |                      ^
    5 |     protected $changes: ChangeTree;
    6 |     protected $items: Map<number, V>;
    7 |     protected $indexes: Map<number, number>;
```

**Comment by endel** [comment]
Thanks a lot for reporting @will-hart, I've added the method signatures for `flat` and `flatMap` which are specific to ESNEXT and it should be okay now on `@colyseus/schema@1.0.0-alpha.25`.

Both methods will throw an exception, though. `ArraySchema` does not support multi-level entries. It is important that `ArraySchema` as a type should be considered an `Array` as well to allow this:

```typescript
class State extends Schema {
  @type(["number"]) grid: number[];
}
const state = new State();
state.grid = [0,0,0,1,1,1,0,1,1]; // you can assign both plain array or ArraySchema here

console.log(state.grid.constructor.name)
// ArraySchema
```

**Comment by will-hart** [comment]
Nice! 👍 

I think it fails for es2020 targets as well. These are required build targets to support dynamic imports.

**Comment by will-hart** [comment]
@colyseus/schema@1.0.0-alpha.25 compiles and runs
