### ISSUE TITLE
schema.discardAllChanges possible bug

### ISSUE THREAD

**Issue by yotamshacham** [colyseus/schema#87]
https://github.com/colyseus/schema/blob/6de127bcf07b9b99d6b13ef1a111db912d23ce97/src/Schema.ts#L747

Code appears to be recursing on the array indices instead of the changes themselves, shouldn't it be:
``const field = fieldsByIndex[changes[index]]; ``

**Comment by endel** [comment]
That was a nice catch @yotamshacham, I wonder what bugs that may have been causing left unnoticed. I've merged your PR #88 and published `@colyseus/schema@0.5.41`. 

There is a new version of `@colyseus/schema` coming up soon (https://github.com/colyseus/schema/pull/82), which has this piece of code rewritten, though. If you'd like to test the new alpha version, it is currently available only for JavaScript: https://www.patreon.com/posts/alpha-colyseus-0-39644075
