### ISSUE TITLE
MapSchema onRemove key is null

### ISSUE THREAD

**Issue by doorbash** [colyseus/schema#90]
Hello,

If you run this sever : https://github.com/doorbash/agar-io-ktx/tree/master/server

```typescript
class GameState extends Schema {
    @type({ map: Player })
    players = new MapSchema<Player>();

    @type({ map: Fruit })
    fruits = new MapSchema<Fruit>();
}

class Player extends Schema {
    @type("float32")
    x: number;

    @type("float32")
    y: number;

    @type("float32")
    radius: number = Constants.PLAYER_INIT_RADIUS;

    @type("int32")
    color: number;

    speed: number = Constants.PLAYER_INIT_SPEED;
    angle = Math.PI * (Math.random() * 2 - 1);
    online: boolean;
}

class Fruit extends Schema {
    @type("string")
    key: string;

    @type("float32")
    x: number;

    @type("float32")
    y: number;

    @type("int32")
    color: number;
}
```

and run this as client: 
```typescript
import { Client } from ".";

const client = new Client("ws://localhost:2560");

(async () => {
    try {
        const room = await client.joinOrCreate<any>("ffa");
        
        console.log("joined successfully", room.sessionId);

        room.state.players.onAdd = (player, i) => {
            // console.log("add player", i);
        }

        room.state.players.onRemove = (player, i) => {
            // console.log("remove player", i);
        }

        room.state.fruits.onAdd = (fruit, i) => {
            if(fruit.key != i) {
                console.error("WTF " + fruit.key  + " != " + i)
            }
            // console.log("fruit added " + i)
        }

        room.state.fruits.onRemove = (fruit, i) => {
            if(fruit.key != i) {
                console.error("WTF " + fruit.key  + " != " + i)
            }
            // console.log("fruit removed " + i)
        }

    } catch (e) {
        console.error("couldn't join room:", e);
    }
})()
```

you see that after a while `fruits.onRemove` function gets called with `i = null`

I noticed that every time this happens, server is sending `NIL` and then sends a `string` instead of an `integer` for map index: 

(numbers are the value of each byte along with description in parentheses)
scroll to the end you to see : *** ***HERE*** ***

```
15		0(i=0:players)		1(l=1)		0(mi=0(SrXraLDh_))		0(i=0:x)		-1(522.31244)		-109(*)		2(*)		68(*)		1(i=1:y)		7(779.1098)		-57(*)		66(*)		68(*)		2(i=2:radius)		0(75.0)		0(*)		-106(*)		66(*)		-63(i=eos)		1(i=1:fruits)		5(l=5)		-64(MAP_NIL)		1(mi=1(fr_1))		-64(MAP_NIL)		-90(mi=fr_537) (***HERE***)		102(*)		114(*)		95(*)		53(*)		51(*)		55(*)		-90		102		114		95		53..........
```

**Comment by endel** [comment]
Hi @doorbash, glad to see you back here! There's a new upcoming version of `@colyseus/schema` that should fix this & a few other bad behaviours of the schema callbacks https://github.com/colyseus/schema/pull/82 

Version 0.14 of Colyseus is already on alpha (`npm install colyseus@alpha`), and it includes the new version of `@colyseus/schema` - the new decoder has been ported only to C# so far (lua, haxe, and c++ are missing)

It would be great if you're willing to make the changes for the Java/Kotlin client as well. I've spent quite some time tinkering on an approach that can be more easily ported, so if you have any questions or suggestions there, it would be really valuable. Thanks a lot!

**Comment by doorbash** [comment]
Hi @endel It's my pleasure :) just wanted to know if I screwed up somewhere haha.
No problem I'll start working on it as soon as I am able to.

**Comment by doorbash** [comment]
Hey @endel it's done! :D
https://github.com/doorbash/colyseus-kotlin/tree/dev

**Comment by endel** [comment]
@doorbash 👏 👏 👏 👏 that's amazing!!
