### ISSUE TITLE
Feature request: ArraySchema/MapSchema "listen" method similar to Schema's "listen" method

### ISSUE THREAD

**Issue by cdata** [colyseus/schema#93]
This feature request arises from [some discussion on Discord](https://discord.com/channels/525739117951320081/564076279444406292/761272900790910987). 

## The challenge

Sometimes it is useful to listen to changes on a state object in multiple "locations" in the implementation of a game. Currently, `ArraySchema` and `MapSchema` support only one listener at a time per category of change. For example:

```ts
// In one part of the game implementation:
room.state.someArray.onAdd = () => {
  console.log('A');
};

// In another part of the game implementation:
room.state.someArray.onAdd = () => {
  console.log('B');
};
```

In the above example, only one of the two observers will be notified, because only one `onAdd` callback is allowed to be set at a time.

It is possible to work-around this limitation by creating an abstraction that enables multiple observers to be registered. For example, @endel suggested such an abstraction on Discord:

```ts
function attachCallback(obj, name, cb) {
    if (obj[name]) {
        const previousCallback = obj[name];
        obj[name] = () => {
            previousCallback();
            cb();
        };
    } else {
        obj[name] = cb;
    }
}
attachCallback(room.state.yourArray, "onAdd", () => {/* cb1 */})
attachCallback(room.state.yourArray, "onAdd", () => {/* cb2 */})
```

## Proposal

Currently, the `Schema` class does not suffer from the same limitation described above. `Schema` has a `listen` method that allows any number of observers to be registered for various types of state change.

This request proposes that a similar `listen` method (or equivalent) be added to `ArraySchema` and `MapSchema` with the intention that multiple observers can register listeners without requiring coordination between them somewhere else in the game implementation.

This would make the state-related objects more coherent with each other.

**Comment by endel** [comment]
Thank you @cdata, this is now available on the latest version 0.15! 🥳 https://docs.colyseus.io/migrating/0.15/#schema-callbacks-api-slightly-changed
