### ISSUE TITLE
Error: "refId" not found: 2

### ISSUE THREAD

**Issue by BjoernRave** [colyseus/schema#95]
Colyseus: 0.14

I deleted my cache and installed the latest schema version.

Now I am getting the following error on the frontend: 

<img width="1440" alt="Screenshot 2020-11-24 at 15 12 29" src="https://user-images.githubusercontent.com/36173920/100105557-69661280-2e5f-11eb-815f-a550b4574787.png">

Joining a room works fine, but when I start the game it crashes. I am unsure, if this is a  bug or just my fault, but I tried to exclude/include a lot of different stuff, but it doesnt help. 

I am also happy to provide access to the repo

**Comment by endel** [comment]
Hi @BjoernRave, 

This error scares me a bit - it has happened before and fixed, but you may have found another way to make it happen - it is likely an encoding problem.

> I am also happy to provide access to the repo
That would help a lot!

Cheers!

**Comment by BjoernRave** [comment]
@endel okay, I sent you an invite to the repo. To get it up and running just convert the `.env.local.example` to `.env.local` in the `web` directory. Run `yarn` in the root and then run `yarn dev:web` If you have any further questions, feel free to ask. we can also hop on a quick call if you want

**Comment by endel** [comment]
Hi @BjoernRave, thanks for sharing the repo again! It turns out the problem was because `room.removeAllListeners()` was also clearing up the serializer data. I've updated `colyseus.js` (`0.14.1`) now to only "teardown" the serializer upon connection close.

Let me know if that works for you!

**Comment by BjoernRave** [comment]
yes, that fixed the problem. Thanks alot once again :)
