### ISSUE TITLE
Extend decorator functionality to allow custom validators

### ISSUE THREAD

**Issue by austinkelleher** [colyseus/schema#96]
## Proposal

Currently, we scan specify a `Schema` decorator's type. It would neat if we could extend this functionality to have custom validation functions on the decorator itself. The validation functions would all be applied in order and throw when the validation fails. Validation would be applied on initial schema instance initialization and when property setters are called.

Here are a few examples:

```typescript
 class MySchema extends Schema {
   @type("number")
    .greaterThan(200)
    .notEqual(5)
    // Any additional custom logic can be applied in the `validate` function
    .validate((v: number) => v + 5 !== 10)
   intValue = 201;
}

const s = new MySchema() // Good!
s.intValue = 199 // Not greater than 200! Throws error!
```

```typescript
 class MySchema extends Schema {
   @type("number").greaterThan(200)
   intValue = 199;
}

new MySchema() // Throws because initial value is not greater than 200!
```

```typescript
 class MySchema extends Schema {
   @type("number").greaterThan(200)
   intValue;
}

new MySchema() // Good! `intValue` is not assigned yet.
```

I'm not sure whether we want this type of functionality built into the core Colyseus schema module, but I wanted to throw out the idea.I have been toying around with implementing this and it can be done fairly easily I think. I would be happy to put up a PR with a few initial decorator validators if it something we want to pursue.

What do you think @endel?

**Comment by austinkelleher** [comment]
I haven't thought too much about the JavaScript API, but perhaps we could enhance the `defineTypes` API to support something like this:

```js
defineTypes(Player, {
  x: {
    type: "number",
    validators: [
      greaterThan(200),
    ]
  },
  y: 'number'
});
```

**Comment by seiyria** [comment]
My primary concern is chaining decorator functions. I would propose something like this instead:

```
@type('number', { greaterThan: 200, notEqual: 5, validate: x => x })
```

Instead. It's a more decorator-friendly API, especially if you wanted to reuse that object, like so:

```
const validPosition = { greaterThan: 0, lessThan: 100 };
@type('number', validPosition) public x;
@type('number', validPosition) public y;
```

**Comment by endel** [comment]
I think validation should not be part of `@colyseus/schema` directly. Having validation embedded here would increase the complexity - this repository alone has reached its peak of complexity on the latest version - I wouldn't like to maintain more complex stuff 😅 

As @vitalyrotari suggested on Discord, it would be best to validate things prior to assigning the value to schema instances.

**Comment by austinkelleher** [comment]
Fair enough! I do think that first-class property validation in schemas is not particularly uncommon (e.g. JSON Schema supports this type of thing). The main motivator is so that we could get to a world where the client and server can leverage the same schema for validation without a bunch of custom JS logic. That would be used in combination with a schema API that allowed passing all of the properties directly to the constructor of the schema class and validating it. 

I'll close this out for now. Thanks for the feedback!
