### ISSUE TITLE
`Schema.clone()` can not handle Proxies (E.g. MapSchema, ArraySchema)

### ISSUE THREAD

**Issue by tobspr** [colyseus/schema#97]
**Example:**
```js
class Example extends Schema {
    @type({ map: PlayerImpl })
    players = new MapSchema<PlayerImpl>();
}

const instance = new Example();
console.log("original:", instance.players);
// original: Proxy {$changes: ChangeTree, $items: Map(0), $indexes: Map(0), $refId: 0, $proxy: true}

console.log("cloned:", instance.clone().players);
// cloned: undefined
```

**Expected behaviour**

The cloned instance should also have the players property.

I suspect this is because the original value is a proxy, which is not handled by the clone method.

**Comment by tobspr** [comment]
Found a temporary workaround:

```js
const cloned = new Example().assign(instance.toJSON());
```

**Comment by endel** [comment]
Thanks for reporting @tobspr, this sounds like a bug cloning deep structures

**Comment by endel** [comment]
It turns out this was a silly mistake during `.clone()` methods 😅  `@colyseus/schema@1.0.6` should fix this!

**Comment by tobspr** [comment]
Awesome, thank you!
