### ISSUE TITLE
MapSchema (and probably others) don't follow the Map specification

### ISSUE THREAD

**Issue by tobspr** [colyseus/schema#98]
The `.get()` method on a `MapSchema` has a return type of of `V`:

 (From MapSchema.d.ts):

```js
export declare class MapSchema<V = any> implements Map<string, V>, SchemaDecoderCallbacks {
  // ....
  get(key: K): V;
  // ...
}
```

But the EcmaScript Map definition (https://tc39.es/ecma262/#sec-map.prototype.get) specifies that the return value can be `undefined` for keys which are not within the map, and thats actually what the MapSchema does too. 

**Issue**

The return type is `V`

**Requested solution**

The return type should be `V | undefined`.

**Comment by endel** [comment]
Thank you for noticing and reporting @tobspr 🎉
